apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nestjs-metrics
  name: nestjs-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-metrics
  template:
    metadata:
      labels:
        app: nestjs-metrics
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '3000'
    spec:
      containers:
        - image: mguay/nestjs-metrics
          name: nestjs-metrics
          ports:
            - containerPort: 3000
